[package]
name = "behavior-bark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }
lazy_static = "1.5"
bevy = { version = "0.14", default_features = false, features = ["bevy_asset"], optional = true }

[features]
default = ["serde"]
bevy = ["dep:bevy"]